'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import Link from 'next/link';
import { Bell, CalendarDays, Camera, Check, CirclePlay, Copy, Eraser, Mic, MicOff, Plus, Search, Send, Trash2, UserPlus, Video, VideoOff } from 'lucide-react';
import styles from '../dashboard/StructuredDashboard.module.css';

type Kind='reunioes'|'agenda'|'contatos'|'gravacoes'|'calculadora'|'octa-ai'|'skills'|'lousa'|'anotar'|'anotacoes'|'notificacoes'|'configuracoes'|'instantanea'|'planos'|'profile';
const seedMeetings=[
 {id:1,title:'Planejamento de Marketing',time:'Hoje, 19:54',people:'4 participantes'},
 {id:2,title:'Reunião Semanal da Diretoria',time:'Amanhã, 10:00',people:'6 participantes'},
 {id:3,title:'Laboratório de Marca',time:'Terça, 14:30',people:'3 participantes'},
];
const seedContacts=[{id:1,name:'Amanda Smith',email:'amanda@octa.app'},{id:2,name:'Marcus Lee',email:'marcus@octa.app'},{id:3,name:'James Miller',email:'james@octa.app'}];
const seedRecordings=[{id:1,title:'Sessão de Fechamento de Vendas',duration:'52 min'},{id:2,title:'Mentoria de Liderança',duration:'1h 12min'}];

function useLocal<T>(key:string,initial:T){
 const [value,setValue]=useState<T>(initial);
 useEffect(()=>{try{const v=localStorage.getItem(key);if(v)setValue(JSON.parse(v))}catch{}},[key]);
 useEffect(()=>{try{localStorage.setItem(key,JSON.stringify(value))}catch{}},[key,value]);
 return [value,setValue] as const;
}

export function WorkspaceSection({kind}:{kind:Kind}){
 const [query,setQuery]=useState('');
 if(kind==='calculadora') return <Calculator/>;
 if(kind==='lousa') return <Whiteboard/>;
 if(kind==='octa-ai') return <AiCoach/>;
 if(kind==='skills') return <Skills/>;
 if(kind==='anotar'||kind==='anotacoes') return <Notes/>;
 if(kind==='configuracoes') return <Settings/>;
 if(kind==='instantanea') return <InstantMeeting/>;
 if(kind==='planos') return <Plans/>;
 if(kind==='profile') return <Profile/>;
 if(kind==='agenda') return <Agenda/>;
 if(kind==='contatos') return <Contacts/>;
 if(kind==='gravacoes') return <Recordings/>;
 if(kind==='notificacoes') return <Notifications/>;
 return <Meetings/>;
}

function Toolbar({query,setQuery,placeholder='Buscar'}:{query:string;setQuery:(v:string)=>void;placeholder?:string}){
 return <div className={styles.wsToolbar}><label><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={placeholder}/></label></div>
}
function Meetings(){
 const [items,setItems]=useLocal('octa.meetings',seedMeetings); const [q,setQ]=useState(''); const [title,setTitle]=useState('');
 const visible=items.filter((x:any)=>x.title.toLowerCase().includes(q.toLowerCase()));
 function add(){if(!title.trim())return;setItems([{id:Date.now(),title:title.trim(),time:'Agora',people:'1 participante'},...items]);setTitle('')}
 return <div className={styles.wsStack}><div className={styles.wsActionRow}><Toolbar query={q} setQuery={setQ} placeholder="Buscar reunião"/><input className={styles.wsInput} value={title} onChange={e=>setTitle(e.target.value)} placeholder="Nome da nova reunião"/><button className={styles.wsPrimary} onClick={add}><Plus size={15}/> Nova reunião</button></div><div className={styles.wsGrid}>{visible.map((m:any)=><article className={styles.wsCard} key={m.id}><span className={styles.wsIcon}><Video size={18}/></span><h3>{m.title}</h3><p>{m.time} · {m.people}</p><div className={styles.wsCardActions}><Link href="/reuniao-instantanea">Entrar</Link><button onClick={()=>navigator.clipboard?.writeText(`${location.origin}/reuniao-instantanea?room=${m.id}`)}><Copy size={13}/> Copiar link</button><button onClick={()=>setItems(items.filter((x:any)=>x.id!==m.id))}><Trash2 size={13}/></button></div></article>)}</div></div>
}
function Agenda(){
 const [events,setEvents]=useLocal('octa.agenda',seedMeetings.map((m,i)=>({...m,day:['Seg','Ter','Qua'][i]}))); const [title,setTitle]=useState('');
 return <div className={styles.wsStack}><div className={styles.wsActionRow}><input className={styles.wsInput} value={title} onChange={e=>setTitle(e.target.value)} placeholder="Adicionar compromisso"/><button className={styles.wsPrimary} onClick={()=>{if(title.trim()){setEvents([...events,{id:Date.now(),title,time:'Hoje, 16:00',people:'OCTA',day:'Hoje'}]);setTitle('')}}}><Plus size={15}/> Agendar</button></div><div className={styles.calendarColumns}>{['Hoje','Seg','Ter','Qua','Qui'].map(day=><section key={day} className={styles.calendarDay}><strong>{day}</strong>{events.filter((e:any)=>e.day===day||day==='Hoje'&&e.day==='Hoje').map((e:any)=><div key={e.id} className={styles.calendarEvent}><CalendarDays size={14}/><b>{e.title}</b><small>{e.time}</small></div>)}</section>)}</div></div>
}
function Contacts(){
 const [items,setItems]=useLocal('octa.contacts',seedContacts); const [q,setQ]=useState(''); const [name,setName]=useState(''); const [email,setEmail]=useState('');
 return <div className={styles.wsStack}><div className={styles.wsActionRow}><Toolbar query={q} setQuery={setQ} placeholder="Buscar contato"/><input className={styles.wsInput} value={name} onChange={e=>setName(e.target.value)} placeholder="Nome"/><input className={styles.wsInput} value={email} onChange={e=>setEmail(e.target.value)} placeholder="E-mail"/><button className={styles.wsPrimary} onClick={()=>{if(name&&email){setItems([...items,{id:Date.now(),name,email}]);setName('');setEmail('')}}}><UserPlus size={15}/> Adicionar</button></div><div className={styles.wsGrid}>{items.filter((c:any)=>(c.name+c.email).toLowerCase().includes(q.toLowerCase())).map((c:any)=><article className={styles.wsCard} key={c.id}><div className={styles.avatarInitial}>{c.name.split(' ').map((s:string)=>s[0]).slice(0,2).join('')}</div><h3>{c.name}</h3><p>{c.email}</p><div className={styles.wsCardActions}><Link href="/reuniao-instantanea">Chamar</Link><a href={`mailto:${c.email}`}>E-mail</a><button onClick={()=>setItems(items.filter((x:any)=>x.id!==c.id))}><Trash2 size={13}/></button></div></article>)}</div></div>
}
function Recordings(){const [q,setQ]=useState('');return <div className={styles.wsStack}><Toolbar query={q} setQuery={setQ} placeholder="Buscar gravação"/><div className={styles.recordHero}><div><span>Gravação em destaque</span><h2>Sessão de Fechamento de Vendas</h2><p>52 min · Replay disponível · OCTA</p><div><button className={styles.wsPrimary}><CirclePlay size={15}/> Assistir</button><Link className={styles.wsSoft} href="/skills">Analisar com OCTA Skills</Link></div></div></div><div className={styles.wsGrid}>{seedRecordings.filter(r=>r.title.toLowerCase().includes(q.toLowerCase())).map(r=><article className={styles.wsCard} key={r.id}><span className={styles.wsIcon}><CirclePlay size={18}/></span><h3>{r.title}</h3><p>{r.duration}</p><div className={styles.wsCardActions}><button>Reproduzir</button><Link href="/skills">Skills</Link></div></article>)}</div></div>}
function Calculator(){const [expr,setExpr]=useState('');const result=useMemo(()=>{try{return expr&&/^[0-9+\-*/(). %]+$/.test(expr)?String(Function(`"use strict";return (${expr})`)()):''}catch{return 'Erro'}},[expr]);return <div className={styles.calc}><input value={expr} onChange={e=>setExpr(e.target.value)} placeholder="0"/><output>{result||'0'}</output><div>{['7','8','9','/','4','5','6','*','1','2','3','-','0','.','%','+'].map(k=><button key={k} onClick={()=>setExpr(expr+k)}>{k}</button>)}<button onClick={()=>setExpr('')} className={styles.calcWide}>Limpar</button><button onClick={()=>setExpr(result==='Erro'?'':result)} className={styles.calcWide}>=</button></div></div>}
function Notes(){const [notes,setNotes]=useLocal('octa.notes',[] as any[]);const [title,setTitle]=useState('');const [body,setBody]=useState('');return <div className={styles.notesLayout}><section className={styles.noteEditor}><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Título da anotação"/><textarea value={body} onChange={e=>setBody(e.target.value)} placeholder="Escreva aqui…"/><button className={styles.wsPrimary} onClick={()=>{if(title||body){setNotes([{id:Date.now(),title:title||'Sem título',body,date:new Date().toLocaleString('pt-BR')},...notes]);setTitle('');setBody('')}}}><Check size={15}/> Salvar anotação</button></section><section className={styles.noteList}>{notes.length===0?<div className={styles.emptyState}>Suas anotações salvas aparecerão aqui.</div>:notes.map((n:any)=><article key={n.id}><strong>{n.title}</strong><p>{n.body}</p><small>{n.date}</small><button onClick={()=>setNotes(notes.filter((x:any)=>x.id!==n.id))}><Trash2 size={13}/></button></article>)}</section></div>}
function AiCoach(){const [messages,setMessages]=useState([{role:'ai',text:'Sou seu OCTA AI Coach. Posso ajudar a transformar suas reuniões em ações mais claras.'}]);const [text,setText]=useState('');function send(){if(!text.trim())return;const q=text;setText('');setMessages([...messages,{role:'you',text:q},{role:'ai',text:'Com base no modo local, eu sugiro: defina o objetivo em uma frase, conduza por blocos curtos e encerre com responsáveis e prazo. Para análise real de transcrição, conecte a API na próxima etapa.'}])}return <div className={styles.aiLayout}><aside><span className={styles.wsIcon}><Bell size={18}/></span><h2>Mais foco.<br/>Mais resultado.</h2><p>Coach local pronto para uso sem backend.</p>{['Onde posso melhorar agora?','Como ser mais objetivo?','Qual meu ponto mais forte?'].map(x=><button key={x} onClick={()=>setText(x)}>{x}</button>)}</aside><section><div className={styles.chatMessages}>{messages.map((m,i)=><div className={m.role==='you'?styles.chatYou:styles.chatAi} key={i}>{m.text}</div>)}</div><div className={styles.chatInput}><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Pergunte sobre sua performance…"/><button onClick={send}><Send size={16}/></button></div></section></div>}
function Skills(){return <div className={styles.skillsDash}><article className={styles.skillScore}><span>Performance geral</span><strong>82<small>/100</small></strong><p>+6,4% vs. semana anterior</p></article><article className={styles.skillMetrics}><h3>Performance por habilidade</h3>{[['Comunicação',88],['Clareza',91],['Escuta',84],['Objetividade',76],['Perguntas',89],['Argumentação',81],['Condução',85]].map(([n,v])=><div key={String(n)}><span>{n}</span><b>{v}</b><i><em style={{width:`${v}%`}}/></i></div>)}</article><article className={styles.skillTip}><span>Ponto forte</span><h3>Você investiga antes de oferecer.</h3><p>Confirma entendimento antes de avançar e mantém a conversa contextualizada.</p></article><article className={styles.skillTip}><span>Oportunidade</span><h3>Ganhar objetividade nas objeções.</h3><p>Meta local: reduzir 18% do tempo de resposta.</p></article></div>}
function Whiteboard(){const ref=useRef<HTMLCanvasElement>(null);const [drawing,setDrawing]=useState(false);function pos(e:any){const c=ref.current!;const r=c.getBoundingClientRect();return[(e.clientX-r.left)*(c.width/r.width),(e.clientY-r.top)*(c.height/r.height)]}function down(e:any){setDrawing(true);const c=ref.current!,ctx=c.getContext('2d')!;const [x,y]=pos(e);ctx.beginPath();ctx.moveTo(x,y);ctx.strokeStyle='#111';ctx.lineWidth=3;ctx.lineCap='round'}function move(e:any){if(!drawing)return;const c=ref.current!,ctx=c.getContext('2d')!;const [x,y]=pos(e);ctx.lineTo(x,y);ctx.stroke()}return <div className={styles.board}><div className={styles.boardTools}><span>Arraste para desenhar</span><button onClick={()=>{const c=ref.current;c?.getContext('2d')?.clearRect(0,0,c.width,c.height)}}><Eraser size={15}/> Limpar</button></div><canvas ref={ref} width={1400} height={800} onPointerDown={down} onPointerMove={move} onPointerUp={()=>setDrawing(false)} onPointerLeave={()=>setDrawing(false)}/></div>}
function Notifications(){const [items,setItems]=useLocal('octa.notifications',[{id:1,title:'Planejamento de Marketing',text:'Sua reunião começa em 1 hora.'},{id:2,title:'OCTA Skills',text:'Sua análise semanal está pronta.'}]);return <div className={styles.wsList}>{items.map((n:any)=><article key={n.id}><span className={styles.wsIcon}><Bell size={17}/></span><div><strong>{n.title}</strong><p>{n.text}</p></div><button onClick={()=>setItems(items.filter((x:any)=>x.id!==n.id))}><Check size={15}/></button></article>)}</div>}
function Settings(){const [prefs,setPrefs]=useLocal('octa.prefs',{notifications:true,sounds:true,compact:false});return <div className={styles.settings}>{Object.entries({notifications:'Notificações',sounds:'Sons da reunião',compact:'Modo compacto'}).map(([k,l])=><label key={k}><span><b>{l}</b><small>Preferência salva neste navegador</small></span><input type="checkbox" checked={(prefs as any)[k]} onChange={e=>setPrefs({...prefs,[k]:e.target.checked})}/></label>)}</div>}
function InstantMeeting(){const video=useRef<HTMLVideoElement>(null);const [stream,setStream]=useState<MediaStream|null>(null);const [cam,setCam]=useState(false);const [mic,setMic]=useState(false);async function enable(){try{const s=await navigator.mediaDevices.getUserMedia({video:true,audio:true});setStream(s);if(video.current)video.current.srcObject=s;setCam(true);setMic(true)}catch{alert('Permita acesso à câmera e ao microfone no navegador.')}}function toggleCam(){stream?.getVideoTracks().forEach(t=>t.enabled=!cam);setCam(!cam)}function toggleMic(){stream?.getAudioTracks().forEach(t=>t.enabled=!mic);setMic(!mic)}return <div className={styles.meetingRoom}><div className={styles.meetingTop}><strong>Estratégia e Crescimento</strong><button onClick={()=>navigator.clipboard?.writeText(location.href)}><Copy size={14}/> Copiar link</button></div><div className={styles.videoPortrait}><video ref={video} autoPlay muted playsInline/><span>Você · câmera 9:16</span>{!stream&&<button onClick={enable}><Camera size={16}/> Ativar câmera</button>}</div><div className={styles.meetingControls}><button onClick={toggleMic} disabled={!stream}>{mic?<Mic size={18}/>:<MicOff size={18}/>}</button><button onClick={toggleCam} disabled={!stream}>{cam?<Camera size={18}/>:<VideoOff size={18}/>}</button><button className={styles.endCall} onClick={()=>{stream?.getTracks().forEach(t=>t.stop());setStream(null);setCam(false);setMic(false)}}>Encerrar</button></div></div>}
function Plans(){return <div className={styles.planGrid}>{[['Starter','R$ 0','Reuniões essenciais'],['Pro','R$ 79,90','Gravações, Skills e AI'],['Business','Sob consulta','Equipes, gestão e controles']].map((p,i)=><article className={i===1?styles.planFeatured:''} key={p[0]}><span>{p[0]}</span><h2>{p[1]}<small>/mês</small></h2><p>{p[2]}</p><button className={styles.wsPrimary}>Escolher plano</button></article>)}</div>}
function Profile(){return <div className={styles.profilePage}><div className={styles.avatarInitial}>DB</div><h2>Denner Biersack</h2><p>Marketing Digital</p><Link className={styles.wsPrimary} href="/configuracoes">Editar preferências</Link></div>}
